name: InfiniteCaptcha CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонування коду
      uses: actions/checkout@v4

    - name: Налаштування .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Відновлення NuGet пакетів
      run: dotnet restore

    - name: Компіляція всього проекту (Release)
      run: dotnet build --no-restore --configuration Release